apiVersion: v2
appVersion: 0.0.0
description: A chart for Service
home: https://github.com/eeveebank/my-repo-name
name: "Service"
version: 0.0.0
dependencies:
#
  - name: backend-generic
    repository: https://mettle-charts.storage.googleapis.com
    version: "4.12.2"
#
